version: '2'
services:
    jhipsterapp-app:
        image: jhipsterapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterapp-postgresql:5432/jhipsterapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterapp-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterapp-postgresql
